/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BestiaryRouteImport } from './routes/bestiary'
import { Route as CraftRouteImport } from './routes/craft'
import { Route as GodsRouteImport } from './routes/gods'
import { Route as PeopleRouteImport } from './routes/people'
import { Route as SpeciesRouteImport } from './routes/species'
import { Route as StoryRouteImport } from './routes/story'
import { Route as SystemsRouteImport } from './routes/systems'
import { Route as ThreadsRouteImport } from './routes/threads'
import { Route as WorldRouteImport } from './routes/world'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestiaryRoute = BestiaryRouteImport.update({
  id: '/bestiary',
  path: '/bestiary',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftRoute = CraftRouteImport.update({
  id: '/craft',
  path: '/craft',
  getParentRoute: () => rootRouteImport,
} as any)
const GodsRoute = GodsRouteImport.update({
  id: '/gods',
  path: '/gods',
  getParentRoute: () => rootRouteImport,
} as any)
const PeopleRoute = PeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeciesRoute = SpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemsRoute = SystemsRouteImport.update({
  id: '/systems',
  path: '/systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadsRoute = ThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldRoute = WorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bestiary': typeof BestiaryRoute
  '/craft': typeof CraftRoute
  '/gods': typeof GodsRoute
  '/people': typeof PeopleRoute
  '/species': typeof SpeciesRoute
  '/story': typeof StoryRoute
  '/systems': typeof SystemsRoute
  '/threads': typeof ThreadsRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bestiary': typeof BestiaryRoute
  '/craft': typeof CraftRoute
  '/gods': typeof GodsRoute
  '/people': typeof PeopleRoute
  '/species': typeof SpeciesRoute
  '/story': typeof StoryRoute
  '/systems': typeof SystemsRoute
  '/threads': typeof ThreadsRoute
  '/world': typeof WorldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bestiary': typeof BestiaryRoute
  '/craft': typeof CraftRoute
  '/gods': typeof GodsRoute
  '/people': typeof PeopleRoute
  '/species': typeof SpeciesRoute
  '/story': typeof StoryRoute
  '/systems': typeof SystemsRoute
  '/threads': typeof ThreadsRoute
  '/world': typeof WorldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bestiary'
    | '/craft'
    | '/gods'
    | '/people'
    | '/species'
    | '/story'
    | '/systems'
    | '/threads'
    | '/world'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bestiary'
    | '/craft'
    | '/gods'
    | '/people'
    | '/species'
    | '/story'
    | '/systems'
    | '/threads'
    | '/world'
  id:
    | '__root__'
    | '/'
    | '/bestiary'
    | '/craft'
    | '/gods'
    | '/people'
    | '/species'
    | '/story'
    | '/systems'
    | '/threads'
    | '/world'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestiaryRoute: typeof BestiaryRoute
  CraftRoute: typeof CraftRoute
  GodsRoute: typeof GodsRoute
  PeopleRoute: typeof PeopleRoute
  SpeciesRoute: typeof SpeciesRoute
  StoryRoute: typeof StoryRoute
  SystemsRoute: typeof SystemsRoute
  ThreadsRoute: typeof ThreadsRoute
  WorldRoute: typeof WorldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestiary': {
      id: '/bestiary'
      path: '/bestiary'
      fullPath: '/bestiary'
      preLoaderRoute: typeof BestiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craft': {
      id: '/craft'
      path: '/craft'
      fullPath: '/craft'
      preLoaderRoute: typeof CraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gods': {
      id: '/gods'
      path: '/gods'
      fullPath: '/gods'
      preLoaderRoute: typeof GodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/people': {
      id: '/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof PeopleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/species': {
      id: '/species'
      path: '/species'
      fullPath: '/species'
      preLoaderRoute: typeof SpeciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/systems': {
      id: '/systems'
      path: '/systems'
      fullPath: '/systems'
      preLoaderRoute: typeof SystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/threads': {
      id: '/threads'
      path: '/threads'
      fullPath: '/threads'
      preLoaderRoute: typeof ThreadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world': {
      id: '/world'
      path: '/world'
      fullPath: '/world'
      preLoaderRoute: typeof WorldRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestiaryRoute: BestiaryRoute,
  CraftRoute: CraftRoute,
  GodsRoute: GodsRoute,
  PeopleRoute: PeopleRoute,
  SpeciesRoute: SpeciesRoute,
  StoryRoute: StoryRoute,
  SystemsRoute: SystemsRoute,
  ThreadsRoute: ThreadsRoute,
  WorldRoute: WorldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
